Repository pallets/jinja, pull requests merged in 2021-05, with the labels that each got.

#1434 Update typing
  CHANGES.rst
  src/jinja2/__init__.py
  src/jinja2/bccache.py
  src/jinja2/compiler.py
  src/jinja2/environment.py
  src/jinja2/lexer.py
  src/jinja2/nodes.py
  src/jinja2/parser.py
  src/jinja2/runtime.py
  src/jinja2/utils.py
Labels: typing

#1435 Update typing
  CHANGES.rst
  src/jinja2/__init__.py
  src/jinja2/bccache.py
  src/jinja2/compiler.py
  src/jinja2/environment.py
  src/jinja2/lexer.py
  src/jinja2/nodes.py
  src/jinja2/parser.py
  src/jinja2/runtime.py
  src/jinja2/utils.py
Labels: typing

#1444 use asyncio.run
  CHANGES.rst
  docs/api.rst
  src/jinja2/environment.py
  tests/test_async.py
Labels: async

#1451 Improve the contributing guide
  CONTRIBUTING.rst
Labels: docs
